[package]
name = "bsharp_parser"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
log = "0.4"
nom = "7"
nom-supreme = "0.8.0"
syntax = { package = "bsharp_syntax", path = "../bsharp_syntax" }
serde = { version = "1.0.219", features = ["derive"] }
phf = { version = "0.11", features = ["macros"] }

[features]
parser_recovery_trace = []
